name: attendance_log_app
description: "Employee attendance with selfie face-match + GPS geofencing (Frappe HR)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  camera: ^0.11.0
  geolocator: ^12.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
